{
    "name": "POS Import Sales Order 404",
    "version": "12.0.1.6.0",
    "summary": "Import and pay for Sales Order in POS",
    "license": "LGPL-3",
    "author": "Ooops",
    "category": "Point of Sale",
    "depends": ["base", "sale", "point_of_sale"],
    "data": ["views/assets.xml", "views/pos_extend.xml"],
    "installable": True,
    "application": False,
    "website": "https://www.ooops403.com",
    "qweb": ["static/src/xml/pos_view.xml"],
    "images": ["static/description/icon.png"],
}
