name: test Odoo addons

on:
  pull_request:
  push:
    branches:
      - "12.0"
      - "12.0-dev"
      - "12.0-ocabot*"

jobs:
  pre-commit:
    name: "Pre-commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  run-test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    needs: [pre-commit]
    container: ghcr.io/sbidoul/oca-ci/py3.6-odoo12.0:latest
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5

    env:
      OCA_GIT_USER_NAME: gslabit
      OCA_GIT_USER_EMAIL: noreply@github.com
      GITHUB_TOKEN: ${{ secrets.GS_TOKEN }}
      REPO: ${{ github.repository }}
      BRANCH: ${{ github.head_ref || github.ref}}

    steps:
      - name: Install openssh-client
        run: apt-get install openssh-client -y

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GS_TOKEN }}

      - uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install addons
        run: oca_install_addons

      - name: Init test database
        run: oca_init_test_database

      - name: Run tests
        run: oca_run_tests

      - name: Makepot
        # prettier-ignore
        if:
          ${{ success() && (contains(github.ref, 'ocabot-merge') == true || github.ref ==
          'refs/heads/12.0-dev') }}
        run: |
          oca_export_and_commit_pot
          git push https://${OCA_GIT_USER_NAME}:${GITHUB_TOKEN}@github.com/${REPO} HEAD:${BRANCH}
